// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Catering.Data;

#nullable disable

namespace ThAmCo.Catering.Data.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    [Migration("20241115164545_ThirdCreate")]
    partial class ThirdCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.HasKey("FoodBookingId");

                    b.HasIndex("MenuId");

                    b.ToTable("FoodBookings");

                    b.HasData(
                        new
                        {
                            FoodBookingId = 1,
                            ClientReferenceId = 1001,
                            MenuId = 1,
                            NumberOfGuests = 50
                        },
                        new
                        {
                            FoodBookingId = 2,
                            ClientReferenceId = 1002,
                            MenuId = 2,
                            NumberOfGuests = 30
                        },
                        new
                        {
                            FoodBookingId = 3,
                            ClientReferenceId = 1003,
                            MenuId = 3,
                            NumberOfGuests = 75
                        },
                        new
                        {
                            FoodBookingId = 4,
                            ClientReferenceId = 1004,
                            MenuId = 4,
                            NumberOfGuests = 20
                        },
                        new
                        {
                            FoodBookingId = 5,
                            ClientReferenceId = 1005,
                            MenuId = 5,
                            NumberOfGuests = 100
                        },
                        new
                        {
                            FoodBookingId = 6,
                            ClientReferenceId = 1006,
                            MenuId = 6,
                            NumberOfGuests = 40
                        },
                        new
                        {
                            FoodBookingId = 7,
                            ClientReferenceId = 1007,
                            MenuId = 7,
                            NumberOfGuests = 60
                        },
                        new
                        {
                            FoodBookingId = 8,
                            ClientReferenceId = 1008,
                            MenuId = 8,
                            NumberOfGuests = 35
                        },
                        new
                        {
                            FoodBookingId = 9,
                            ClientReferenceId = 1009,
                            MenuId = 9,
                            NumberOfGuests = 45
                        },
                        new
                        {
                            FoodBookingId = 10,
                            ClientReferenceId = 1010,
                            MenuId = 10,
                            NumberOfGuests = 25
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Grilled Chicken",
                            UnitPrice = 12.5f
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "Vegan Salad",
                            UnitPrice = 8f
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Chocolate Cake",
                            UnitPrice = 5f
                        },
                        new
                        {
                            FoodItemId = 4,
                            Description = "Fruit Salad",
                            UnitPrice = 4.5f
                        },
                        new
                        {
                            FoodItemId = 5,
                            Description = "Fish and Chips",
                            UnitPrice = 10f
                        },
                        new
                        {
                            FoodItemId = 6,
                            Description = "Macaroni and Cheese",
                            UnitPrice = 6.5f
                        },
                        new
                        {
                            FoodItemId = 7,
                            Description = "Caesar Salad",
                            UnitPrice = 7f
                        },
                        new
                        {
                            FoodItemId = 8,
                            Description = "Pasta Primavera",
                            UnitPrice = 9f
                        },
                        new
                        {
                            FoodItemId = 9,
                            Description = "Ice Cream Sundae",
                            UnitPrice = 3.5f
                        },
                        new
                        {
                            FoodItemId = 10,
                            Description = "Pancakes",
                            UnitPrice = 4f
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "Classic Menu"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "Vegetarian Menu"
                        },
                        new
                        {
                            MenuId = 3,
                            MenuName = "Vegan Menu"
                        },
                        new
                        {
                            MenuId = 4,
                            MenuName = "Kids Menu"
                        },
                        new
                        {
                            MenuId = 5,
                            MenuName = "Seafood Menu"
                        },
                        new
                        {
                            MenuId = 6,
                            MenuName = "Italian Menu"
                        },
                        new
                        {
                            MenuId = 7,
                            MenuName = "BBQ Menu"
                        },
                        new
                        {
                            MenuId = 8,
                            MenuName = "Dessert Menu"
                        },
                        new
                        {
                            MenuId = 9,
                            MenuName = "Breakfast Menu"
                        },
                        new
                        {
                            MenuId = 10,
                            MenuName = "Lunch Menu"
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.ToTable("MenuFoodItems");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 1
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 3
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 2
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 4
                        },
                        new
                        {
                            MenuId = 3,
                            FoodItemId = 2
                        },
                        new
                        {
                            MenuId = 3,
                            FoodItemId = 7
                        },
                        new
                        {
                            MenuId = 4,
                            FoodItemId = 6
                        },
                        new
                        {
                            MenuId = 4,
                            FoodItemId = 9
                        },
                        new
                        {
                            MenuId = 5,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 5,
                            FoodItemId = 8
                        },
                        new
                        {
                            MenuId = 6,
                            FoodItemId = 8
                        },
                        new
                        {
                            MenuId = 6,
                            FoodItemId = 7
                        },
                        new
                        {
                            MenuId = 7,
                            FoodItemId = 1
                        },
                        new
                        {
                            MenuId = 7,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 8,
                            FoodItemId = 3
                        },
                        new
                        {
                            MenuId = 8,
                            FoodItemId = 9
                        },
                        new
                        {
                            MenuId = 9,
                            FoodItemId = 10
                        },
                        new
                        {
                            MenuId = 9,
                            FoodItemId = 4
                        },
                        new
                        {
                            MenuId = 10,
                            FoodItemId = 6
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.Menu", "Menu")
                        .WithMany("FoodBookings")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.Data.FoodItem", "FoodItem")
                        .WithMany("MenuFoodItems")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.Data.Menu", "Menu")
                        .WithMany("MenuFoodItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Navigation("MenuFoodItems");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Navigation("FoodBookings");

                    b.Navigation("MenuFoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
